name: Download latest translations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"
  
permissions: write-all

jobs:
  download-translations-with-crowdin:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Checkout DevTools
        uses: actions/checkout@v3
        with:
          ref: feature/refactoring
          repository: Cancri55E/WowUkrainizer-DevTools
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: DevTools

      - name: Restore DevTools NuGet packages
        run: dotnet restore ${{ github.workspace }}/DevTools/WowUkrainizer.DevTools/WowUkrainizer.DevTools.csproj

      - name: Build DevTools project
        run: dotnet build ${{ github.workspace }}/DevTools/WowUkrainizer.DevTools/WowUkrainizer.DevTools.csproj --configuration Release --no-restore

      - name: Download latest translations from Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          download_language: 'uk'
          export_only_approved: false
          create_pull_request: false
          push_translations: false
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Run DevTools project
        id: run_update_translation_cmd
        run: |
          UPDATE_TRANSLATION_RESULT=$(dotnet run --project ${{ github.workspace }}/DevTools/WowUkrainizer.DevTools/WowUkrainizer.DevTools.csproj --configuration Release -- --m "update-translation" --ds "${{ github.workspace }}/Data.db" --t "${{ github.workspace }}/uk" 2>update-translation-log.txt)
          echo "::set-output name=output::$UPDATE_TRANSLATION_RESULT"

      - name: Display update translation log
        run: |
          cat update-translation-log.txt
          echo "The output of the dotnet command was ${{ steps.run_update_translation_cmd.outputs.output }}"

      - name: Commit translations
        if: steps.run_update_translation_cmd.outputs.output != '0'
        uses: EndBug/add-and-commit@v9
        with:
          message: Update Data.db and uk/*.json with latest translations from Crowdin
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: 'Data.db uk/*'
          
      - name: Trigger WowUkrainizer repo to publish alpha version
        if: steps.run_update_translation_cmd.outputs.output != '0'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Cancri55E/WowUkrainizer/actions/workflows/package.yml/dispatches \
          -d '{"ref":"master"}'

